version: '3.8'

services:
  # MCP Tools Server
  mcp-tools-server:
    build:
      context: ./mcp-tools-server
      dockerfile: Dockerfile
    image: mcp-tools-server:latest
    container_name: mcp-tools-server
    ports:
      - "3001:3001"
    networks:
      - agent-hub-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent Hub API
  agent-hub-api:
    build:
      context: ./agent-hub-api
      dockerfile: Dockerfile
    image: agent-hub-api:latest
    container_name: agent-hub-api
    ports:
      - "8000:8000"
    environment:
      - MCP_TOOLS_SERVER_URL=http://mcp-tools-server:3001
    env_file:
      - .env
    networks:
      - agent-hub-network
    depends_on:
      mcp-tools-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Agent Hub Frontend
  agent-hub:
    build:
      context: ./agent-hub
      dockerfile: Dockerfile
    image: agent-hub:latest
    container_name: agent-hub
    ports:
      - "4200:80"
    networks:
      - agent-hub-network
    depends_on:
      agent-hub-api:
        condition: service_healthy
    # Environment variables for Angular at build time
    environment:
      - API_BASE_URL=/api

networks:
  agent-hub-network:
    driver: bridge