default_language_version:
  python: python3.9

repos:
  # Black - opinionated code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # isort - sort & group imports (compatible with Black)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

  # Autoflake - remove unused imports/variables
  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]

  # Flake8 - linter (final safety net after auto-fixes)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=150", "--extend-ignore=E203,W503,E722"]

exclude: '(^\.venv/|^\.idea/|^\.env$)'
