name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # org/repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set image ref (lowercase)
        id: img
        run: |
          REF="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "ref=${REF,,}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (conditionally) push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.img.outputs.ref }}:${{ github.run_number }}
            ${{ steps.img.outputs.ref }}:sha-${{ github.sha }}
            ${{ steps.img.outputs.ref }}:latest
